spring:
  application:
    name: eureka-service-discovery-server
server:
  port:
    ${port:8761}
  servlet:
    context-path: /eureka
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false