spring:
  application:
    name: eureka-service-discovery-server
  security:
    user:
      name: desenv
      password: desenv
server:
  port:
    ${port:8761}
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false